@include('./../../newadminpanel/header')
@include('./../../newadminpanel/topnavabr')
@include('./../../newadminpanel/sidebar')
@include('adminpages.viewcategory.maincontent')
@include('./../../newadminpanel/footer')