@include('./../../newadminpanel/header')
@include('./../../newadminpanel/topnavabr')
@include('./../../newadminpanel/sidebar')
@include('adminpages.viewallengr.maincontent')
@include('./../../newadminpanel/footer')