@include('./../../newadminpanel/header')
@include('./../../newadminpanel/topnavabr')
@include('./../../newadminpanel/sidebar')
@include('adminpages/client/maincontent')
@include('./../../newadminpanel/footer')